Add host, hostlist, hostcount, service, servicelist, servicecount, pe…
ulumuri/go-nagios pull request #6
Opened 2020-09-29 17:26 UTC by DanielSz50

…rformancedata

2020-09-30 11:29 UTC, amwolff requested changes

2020-09-30 11:29 UTC, amwolff commented on nagios/status.go
> +	q.URLQuery.Set("endtime", strconv.FormatInt(g.EndTime, 10))
Status JSON CGI can have these fields empty.

2020-09-30 11:29 UTC, amwolff commented on nagios/status.go
> +	HostList  map[string]json.RawMessage `json:"hostlist"`
Could it be unmarshaled into a `map[string]string` or something like that?

2020-09-30 11:29 UTC, amwolff commented on nagios/status.go
> +	q.URLQuery.Set("endtime", strconv.FormatInt(g.EndTime, 10))
Status JSON CGI can have these fields empty.

2020-09-30 11:29 UTC, amwolff commented on nagios/status.go
> +	return h.build("host")
You don't need the intermediate method here (`build` can be just `Build`).

2020-09-30 11:29 UTC, amwolff commented on nagios/status.go
> +	return s.build("service")
ditto.

2020-09-30 11:29 UTC, amwolff commented on nagios/status.go
> +	return p.build("performancedata")
ditto.

2020-09-30 11:29 UTC, amwolff commented on nagios/status.go
> +type Performance struct {
Follow the convention set earlier. Move this type after the `PerformanceData` type.

BTW It's super easy to get lost here. Maybe we could utilize the `type ( ... )` clause to group types used in the same context?

2020-09-30 11:29 UTC, amwolff commented on nagios/status.go
> +	One5Min int `json:"15min"`
It's fifteen.

2020-09-30 11:29 UTC, amwolff commented on nagios/status.go
> +type ActiveOndemandHostChecks struct {
Use camelCase.

2020-09-30 11:29 UTC, amwolff commented on nagios/status.go
> +type ActiveOndemandServiceChecks struct {
ditto.

2020-09-30 11:29 UTC, amwolff commented on nagios/status.go
> +type Programstatus struct {
ditto.

2020-09-30 14:51 UTC, DanielSz50 commented on nagios/status.go
> +	return h.build("host")
I thought it looks slightly better when we code it this way even if it's unnecessary.

2020-09-30 14:58 UTC, DanielSz50 commented on nagios/status.go
> +type Performance struct {
Cool, I didn't know about that functionality.

2020-09-30 14:59 UTC, DanielSz50 commented on nagios/status.go
> +	HostList  map[string]json.RawMessage `json:"hostlist"`
Sure thing, my mistake.

2020-09-30 14:59 UTC, DanielSz50 commented on nagios/status.go
> +	q.URLQuery.Set("endtime", strconv.FormatInt(g.EndTime, 10))
Right.

2020-09-30 15:01 UTC, DanielSz50 commented on nagios/status.go
> +type ActiveOndemandHostChecks struct {
My mistake.

2020-09-30 15:02 UTC, DanielSz50 commented on nagios/status.go
> +	q.URLQuery.Set("endtime", strconv.FormatInt(g.EndTime, 10))
Right.

2020-10-01 14:02 UTC, amwolff submitted a review, later dismissed
LGTM, but we mustn't forget tests. We need both unit + `internal/integration`.

The bottom line is: merge this if you need this now, add tests later or add tests now.

2020-10-01 15:15 UTC, DanielSz50 commented
I will include tests later that day.

2020-10-01 22:09 UTC, amwolff requested changes

2020-10-01 22:09 UTC, amwolff commented on nagios/status.go
> +	}
Maybe we should adjust the `SetNonEmpty` method. It shouldn't hurt the rest of the client code, I think.

Of course not requesting that in this patch set.

2020-10-01 22:09 UTC, amwolff commented on nagios/status.go
> +	HostList  map[string]json.RawMessage `json:"hostlist"`
Hm, I'm guessing the `map[string]string` failed to work with `Enumerate` switched. Strange.

2020-10-01 22:09 UTC, amwolff commented on nagios/status.go
> +	}
I'm not sure whether we should include both times when only one is present.

2020-10-01 22:09 UTC, amwolff commented on nagios/status.go
> +	// CheckOptions with bitmask turns to the array
```suggestion
	// CheckOptions with bitmask turns into an array.
```

2020-10-01 22:09 UTC, amwolff commented on nagios/status_test.go
> +func TestServieListRequest_Build(t *testing.T) {
```suggestion
func TestServiceListRequest_Build(t *testing.T) {
```

BTW you can generate these test if you're using some kind of IDE (although cleaning them up is a bit of work).

2020-10-01 22:09 UTC, amwolff commented on nagios/status_test.go
> +	}
It's unused.

2020-10-01 22:09 UTC, amwolff commented on nagios/status_test.go
> +	}
ditto.

2020-10-01 22:09 UTC, amwolff commented on nagios/status_test.go
> +	}
ditto.

2020-10-04 10:33 UTC, DanielSz50 commented on nagios/status.go
> +	HostList  map[string]json.RawMessage `json:"hostlist"`
After checking the showDetails option JSON looks completely different.

2020-10-04 10:38 UTC, DanielSz50 commented on nagios/status.go
> +	}
Adjusted, let me know if it's ok.

2020-10-04 13:18 UTC, amwolff requested changes
I was thinking of a different modification to the `SetNonEmpty`. Let me know what you think.

2020-10-04 13:18 UTC, amwolff commented on nagios/query.go
>  	if len(value) > 0 {
I was thinking about something more like this. Exclude all zero-values:
```suggestion
	if len(value) > 0 && value != "0" {
```

2020-10-04 13:18 UTC, amwolff commented on nagios/status.go
> +//TODO(DanielSz50): Handle showDetails check properly
```suggestion
// TODO(DanielSz50): Handle showDetails check properly.
```

Oh, yeah, we should have that linter enabled.

2020-10-04 13:18 UTC, amwolff commented on nagios/status.go
> +	HostList  map[string]json.RawMessage `json:"hostlist"`
Ack.

2020-10-04 13:18 UTC, amwolff commented on nagios/status.go
> +	// CheckOptions with bitmask turns to the array
Forgot about this comment.

2020-10-04 15:28 UTC, DanielSz50 commented
I didn't want to accidentally omit numeric values that could be set to 0, but now I see it shouldn't be a problem.

2020-10-05 19:08 UTC, amwolff commented on nagios/status.go
> +	}
Looks good to me :+1:

2020-10-05 19:10 UTC, amwolff approved these changes

2020-10-06 05:46 UTC, merged